library(memoise)
library(dplyr)
library(ggplot2)
library(tidyr)
library(ggmap)
library(cluster)   
library(tm)
library(topicmodels)
library(slam)
library(SnowballC)
library(wordcloud)
library(plotly)
library(shinythemes)

boroughs <- c("Bronx","Staten Island")
load("bronx_dtm_termCount.rda")
load("staten_dtm_termCount.rda")
load("post.lda.bronx.rda")
load("post.lda.staten")
